name: 'Run NPM Package Hijacker'

description: 'Installs and runs a faux NPM registry'

author: 'Richard Moore <me@ricmoo.com>'

runs:
  using: "composite"
  steps:
    - run: nohup npm start &
      shell: bash
