name: 'Run NPM Package Hijacker'

description: 'Installs and runs a faux NPM registry'

author: 'Richard Moore <me@ricmoo.com>'

runs:
  using: "composite"
  steps:
    - run: git clone https://github.com/ethers-io/hijack-npm-action.git
      shell: bash
    - run: nohup node hijack-npm-action/index.js &
      shell: bash
